name: send-glove-text
run-name: Sending a reminder to put gloves on to ${{ github.actor }}
on:
  schedule:
    - cron: "30 12 * * *"

jobs:
  morning-temperature-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run script
        env:
          WEATHERSTACK_API_KEY: ${{ secrets.WEATHERSTACK_API_KEY }}
          WEATHERSTACK_QUERY: ${{ secrets.WEATHERSTACK_QUERY }}
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
          SMS_GATEWAY: ${{ secrets.SMS_GATEWAY }}
        run: |
          python script.py
